# Generated by Django 3.1 on 2021-02-03 21:34

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=hello.models.user_directory_path)),
            ],
        ),
    ]
