# Generated by Django 3.1 on 2021-02-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210203_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='upload',
            new_name='private_upload',
        ),
    ]
