# Generated by Django 3.1 on 2021-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210204_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='public_upload',
            field=models.FileField(blank=True, null=True, storage='django_hello.backend.AzurePublicStorage', upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='private_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
