# Generated by Django 3.1 on 2021-02-05 20:00

from django.db import migrations, models
import django_hello.backend


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210205_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='private_upload',
            field=models.FileField(blank=True, null=True, storage=django_hello.backend.PrivateStorage(), upload_to='private_uploads'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='public_upload',
            field=models.FileField(blank=True, null=True, storage=django_hello.backend.PublicStorage(), upload_to='public_uploads'),
        ),
    ]
